export const TOKEN_KEY = 'token'
export const LANG = 'language'
export const TAGS_VIEW = 'tagsView'
export const LOGIN_CALLBACK = 'loginCallback'
export const APP_NAME = 'wukong'
export const CLIENT_ENCRYPT_PUBLIC_KEY = 'clientEncryptPublicKey'
